#!/bin/sh
. $(dirname "$0")/init.sh

# Tests parsing of some messages generated by Bind named.
#
# This test depends on test-syslog-logs.


logfile="$HERE/samples/named.log"

# Jun  1 01:01:01 robant named[1400]: client 12.34.56.78#40162 (my-domain.tld): query (cache) 'my-domain.tld/SOA/IN' denied
line="$(logline "$logfile" 1 | LEX)"
reApp="$(re_tok $T_APP "named\[1400\]:?")"
reCli="$(re_tok $T_CLIENT "client 12.34.56.78#40162")"
reInf="$(re_tok $T_INFO "\(my-domain.tld\):?")"
reMsg="$(re_tok $T_MESSAGE "query .*")"
assertRegex "$line" "/$reApp$reCli$reInf$reMsg/"


success
