#!/bin/sh
. $(dirname "$0")/init.sh

# Tests parsing of some messages generated by SSH.
# These formats are not really SSH-specific,
# this is just a place as good as any to test them.
#
# This test depends on test-syslog-logs.


logfile="$HERE/samples/ssh.log"


# Sep  7 13:53:43 myhost1 ssh[11000]: debug3: hostkeys_foreach: reading file "/home/me/.ssh/known_hosts"
line="$(logline "$logfile" 1 | LEX)"
assertRegex "$line" "/$(re_tok $T_APP "ssh\[11000\]:?")/"
assertRegex "$line" "/$(re_tok $T_LOGLEVEL "debug3:?")/"
assertRegex "$line" "/$(re_tok $T_MESSAGE "hostkeys_foreach: reading file.*")/"

# Sep  7 13:53:43 myhost1 ssh[11000]: debug3: record_hostkey: found key type ECDSA in file /home/me/.ssh/known_hosts:16
line="$(logline "$logfile" 2 | LEX)"
assertRegex "$line" "/$(re_tok $T_MESSAGE "record_hostkey: found key type ECDSA")/"
assertRegex "$line" "/$(re_tok $T_TRACE "in file \/home\/me\/\.ssh\/known_hosts:16")/"

# Sep  7 13:53:38 myhost1 ssh[11000]: debug1: /home/me/.ssh/config line 22: Applying options for myhost6
line="$(logline "$logfile" 3 | LEX)"
assertRegex "$line" "/$(re_tok $T_TRACE "\/home\/me\/\.ssh\/config line 22:?")/"
assertRegex "$line" "/$(re_tok $T_MESSAGE ":? ?Applying options for myhost6")/"


success
